services:
  - type: web
    name: smartyoz-app
    runtime: node
    buildCommand: npm install --legacy-peer-deps --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: BASE_URL
        sync: false
